template = "https://github.com/giellalt/template-lang-und"
rev_id = 305
template_sha = "64df68fecb78cef7f709bfe67c09affe7c3b0c38"

[replacements]
__GLOTTOLOG_ID__ = "stan1288"
__REPO__ = "lang-spa-x-ext-apertium"
__UND2C__ = "es"
__UNDEFINED__ = "Spanish"
__UND__ = "spa"
