template = "https://github.com/giellalt/template-lang-und"
rev_id = 334
template_sha = "295433261311db06974764ace81fbb35d1f5ac28"

[replacements]
__GLOTTOLOG_ID__ = "stan1288"
__REPO__ = "lang-spa-x-ext-apertium"
__UND2C__ = "es"
__UNDEFINED__ = "Spanish"
__UND__ = "spa"
