template = "https://github.com/giellalt/template-lang-und"
rev_id = 289
template_sha = "599009dae90448ef6fe32b71f7a6880293f3d546"

[replacements]
__GLOTTOLOG_ID__ = "stan1288"
__REPO__ = "lang-spa-x-ext-apertium"
__UND2C__ = "es"
__UNDEFINED__ = "Spanish"
__UND__ = "spa"
